esphome:
  name: sololightbeer

esp8266:
  board: nodemcuv2

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Sololightbeer Fallback Hotspot"
    password: "nTig01EaXGdZ"

captive_portal:

light:
  - platform: rgb
    name: "RGB Light"
    id: rgb_light
    red: red_output
    green: green_output
    blue: blue_output
    default_transition_length: 1s
    effects:
      - random:
      - strobe:
      - flicker:

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: red_output
    inverted: true
    
  - platform: esp8266_pwm
    pin: D2
    frequency: 1000 Hz
    id: green_output
    inverted: true
    
  - platform: esp8266_pwm
    pin: D5
    frequency: 1000 Hz
    id: blue_output
    inverted: true
